### ISSUE TITLE
Entering a chord sequence and playing along

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bigman73/practicesharp#17]
```
Can practicesharp be used to enter a chord progression and play it back (for as 
many times as I choose) so I can play along or solo-along with the chords?

Thanks


```

Original issue reported on code.google.com by `mburk8...@gmail.com` on 22 Sep 2013 at 11:52

**Comment by bigman73** [comment]
Out of scope for Practice#
The application plays audio files.
If a chord progression is required for playback then it can be generated by playing the guitar and recording it into an audio file, then play the audio file in Practice#
